### ISSUE TITLE
Test with JRuby 9 is failed

### ISSUE THREAD

**Issue by pocke** [buruzaemon/natto#74]
Test with JRuby 9 is failed, so we cannot add JRuby 9 to the CI matrix.

```
$ bundle exec rake
/home/pocke/.rbenv/versions/jruby-9.2.5.0/bin/jruby  test/test_natto.rb 
Run options: --seed 45048

# Running:

[INFO] setup: could not delete test.dic, you might want to remove manually.
reading /home/pocke/ghq/github.com/buruzaemon/natto/test/natto/test_userdic.csv ... 1
emitting double-array: 100% |###########################################| 

done!
.[INFO] setup: could not delete test.dic, you might want to remove manually.
reading /home/pocke/ghq/github.com/buruzaemon/natto/test/natto/test_userdic.csv ... 1
emitting double-array: 100% |###########################################| 

done!
.[INFO] setup: could not delete test.dic, you might want to remove manually.
reading /home/pocke/ghq/github.com/buruzaemon/natto/test/natto/test_userdic.csv ... 1
emitting double-array: 100% |###########################################| 

done!
.[INFO] setup: could not delete test.dic, you might want to remove manually.
reading /home/pocke/ghq/github.com/buruzaemon/natto/test/natto/test_userdic.csv ... 1
emitting double-array: 100% |###########################################| 

done!
.......:lattice-level is DEPRECATED, please use :marginal or :nbest
:lattice-level is DEPRECATED, please use :marginal or :nbest
:lattice-level is DEPRECATED, please use :marginal or :nbest
:lattice-level is DEPRECATED, please use :marginal or :nbest
:lattice-level is DEPRECATED, please use :marginal or :nbest
........E...E.......:lattice-level is DEPRECATED, please use :marginal or :nbest
:lattice-level is DEPRECATED, please use :marginal or :nbest
:lattice-level is DEPRECATED, please use :marginal or :nbest
:lattice-level is DEPRECATED, please use :marginal or :nbest
:lattice-level is DEPRECATED, please use :marginal or :nbest
..............

Finished in 1.511805s, 29.1043 runs/s, 398.8610 assertions/s.

  1) Error:
TestMeCab#test_parse_tostr_feature_constraints:
Natto::MeCabError: 
    /home/pocke/ghq/github.com/buruzaemon/natto/lib/natto/natto.rb:339:in `block in initialize'
    /home/pocke/ghq/github.com/buruzaemon/natto/lib/natto/natto.rb:479:in `parse'
    /home/pocke/ghq/github.com/buruzaemon/natto/test/natto/tc_mecab.rb:476:in `test_parse_tostr_feature_constraints'

  2) Error:
TestMeCab#test_parse_tonodes_feature_constraints:
Natto::MeCabError: 
    /home/pocke/ghq/github.com/buruzaemon/natto/lib/natto/natto.rb:420:in `block in initialize'
    org/jruby/RubyGenerator.java:102:in `each'
    org/jruby/RubyEnumerator.java:326:in `each'
    org/jruby/RubyEnumerator.java:332:in `each'
    /home/pocke/ghq/github.com/buruzaemon/natto/test/natto/tc_mecab.rb:645:in `test_parse_tonodes_feature_constraints'

44 runs, 603 assertions, 0 failures, 2 errors, 0 skips
rake aborted!
Command failed with status (1): [/home/pocke/.rbenv/versions/jruby-9.2.5.0/...]
/home/pocke/ghq/github.com/buruzaemon/natto/Rakefile:11:in `block in <main>'
/home/pocke/.rbenv/versions/jruby-9.2.5.0/bin/bundle:23:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

The cause is https://github.com/jruby/jruby/issues/5513 . Probably we can add JRuby 9 to the CI matrix after this bug is fixed.

**Comment by buruzaemon** [comment]
Thank you very much for raising this issue, @pocke.  I will have a look into this over the weekend.

**Comment by buruzaemon** [comment]
Confirmed that JRuby 9 tests are failing in Travis. 

We will remove JRuby 9 from the test matrix for now.
